//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiprueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int CodigoProducto { get; set; }
        public string Identificacion { get; set; }
        public string NombreProducto { get; set; }
        public int Existencias { get; set; }
        public string Bodega { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
