//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiprueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroLogin
    {
        public int IdLogin { get; set; }
        public string Identificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string token { get; set; }
        public string Contrasena { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
